#!/bin/bash

cp src/1.html src/2.html
cp src/1.html src/3.html
cp src/1.html src/4.html
cp src/1.html src/5.html
cp src/1.html src/6.html
cp src/1.html src/7.html
cp src/1.html src/8.html
cp src/1.html src/9.html
cp src/1.html src/10.html
cp src/1.html src/11.html
cp src/1.html src/12.html
cp src/1.html src/13.html
cp src/1.html src/14.html
cp src/1.html src/15.html
cp src/1.html src/16.html
cp src/1.html src/17.html
cp src/1.html src/18.html
cp src/1.html src/19.html
cp src/1.html src/20.html
cp src/1.html src/21.html
cp src/1.html src/22.html
cp src/1.html src/23.html
cp src/1.html src/24.html
cp src/1.html src/25.html
cp src/1.html src/26.html
cp src/1.html src/27.html
cp src/1.html src/28.html
cp src/1.html src/29.html
cp src/1.html src/30.html
cp src/1.html src/31.html
cp src/1.html src/32.html
cp src/1.html src/33.html
cp src/1.html src/34.html
cp src/1.html src/35.html
cp src/1.html src/36.html
cp src/1.html src/37.html
cp src/1.html src/38.html
cp src/1.html src/39.html
cp src/1.html src/40.html
cp src/1.html src/41.html
cp src/1.html src/42.html
cp src/1.html src/43.html
cp src/1.html src/44.html
cp src/1.html src/45.html
cp src/1.html src/46.html
cp src/1.html src/47.html
cp src/1.html src/48.html
cp src/1.html src/49.html
cp src/1.html src/50.html

cp src/js/1.js src/js/2.js
cp src/js/1.js src/js/3.js
cp src/js/1.js src/js/4.js
cp src/js/1.js src/js/5.js
cp src/js/1.js src/js/6.js
cp src/js/1.js src/js/7.js
cp src/js/1.js src/js/8.js
cp src/js/1.js src/js/9.js
cp src/js/1.js src/js/10.js
cp src/js/1.js src/js/11.js
cp src/js/1.js src/js/12.js
cp src/js/1.js src/js/13.js
cp src/js/1.js src/js/14.js
cp src/js/1.js src/js/15.js
cp src/js/1.js src/js/16.js
cp src/js/1.js src/js/17.js
cp src/js/1.js src/js/18.js
cp src/js/1.js src/js/19.js
cp src/js/1.js src/js/20.js
cp src/js/1.js src/js/21.js
cp src/js/1.js src/js/22.js
cp src/js/1.js src/js/23.js
cp src/js/1.js src/js/24.js
cp src/js/1.js src/js/25.js
cp src/js/1.js src/js/26.js
cp src/js/1.js src/js/27.js
cp src/js/1.js src/js/28.js
cp src/js/1.js src/js/29.js
cp src/js/1.js src/js/30.js
cp src/js/1.js src/js/31.js
cp src/js/1.js src/js/32.js
cp src/js/1.js src/js/33.js
cp src/js/1.js src/js/34.js
cp src/js/1.js src/js/35.js
cp src/js/1.js src/js/36.js
cp src/js/1.js src/js/37.js
cp src/js/1.js src/js/38.js
cp src/js/1.js src/js/39.js
cp src/js/1.js src/js/40.js
cp src/js/1.js src/js/41.js
cp src/js/1.js src/js/42.js
cp src/js/1.js src/js/43.js
cp src/js/1.js src/js/44.js
cp src/js/1.js src/js/45.js
cp src/js/1.js src/js/46.js
cp src/js/1.js src/js/47.js
cp src/js/1.js src/js/48.js
cp src/js/1.js src/js/49.js
cp src/js/1.js src/js/50.js

cp src/css/1.css src/css/2.css
cp src/css/1.css src/css/3.css
cp src/css/1.css src/css/4.css
cp src/css/1.css src/css/5.css
cp src/css/1.css src/css/6.css
cp src/css/1.css src/css/7.css
cp src/css/1.css src/css/8.css
cp src/css/1.css src/css/9.css
cp src/css/1.css src/css/10.css
cp src/css/1.css src/css/11.css
cp src/css/1.css src/css/12.css
cp src/css/1.css src/css/13.css
cp src/css/1.css src/css/14.css
cp src/css/1.css src/css/15.css
cp src/css/1.css src/css/16.css
cp src/css/1.css src/css/17.css
cp src/css/1.css src/css/18.css
cp src/css/1.css src/css/19.css
cp src/css/1.css src/css/20.css
cp src/css/1.css src/css/21.css
cp src/css/1.css src/css/22.css
cp src/css/1.css src/css/23.css
cp src/css/1.css src/css/24.css
cp src/css/1.css src/css/25.css
cp src/css/1.css src/css/26.css
cp src/css/1.css src/css/27.css
cp src/css/1.css src/css/28.css
cp src/css/1.css src/css/29.css
cp src/css/1.css src/css/30.css
cp src/css/1.css src/css/31.css
cp src/css/1.css src/css/32.css
cp src/css/1.css src/css/33.css
cp src/css/1.css src/css/34.css
cp src/css/1.css src/css/35.css
cp src/css/1.css src/css/36.css
cp src/css/1.css src/css/37.css
cp src/css/1.css src/css/38.css
cp src/css/1.css src/css/39.css
cp src/css/1.css src/css/40.css
cp src/css/1.css src/css/41.css
cp src/css/1.css src/css/42.css
cp src/css/1.css src/css/43.css
cp src/css/1.css src/css/44.css
cp src/css/1.css src/css/45.css
cp src/css/1.css src/css/46.css
cp src/css/1.css src/css/47.css
cp src/css/1.css src/css/48.css
cp src/css/1.css src/css/49.css
cp src/css/1.css src/css/50.css